/*
 * generated by Xtext 2.30.0
 */
package lsi.us.es.mis.xtext.parser.antlr;

import com.google.inject.Inject;
import lsi.us.es.mis.xtext.parser.antlr.internal.InternalMyStateMachineParser;
import lsi.us.es.mis.xtext.services.MyStateMachineGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MyStateMachineParser extends AbstractAntlrParser {

	@Inject
	private MyStateMachineGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMyStateMachineParser createParser(XtextTokenStream stream) {
		return new InternalMyStateMachineParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "StateMachine";
	}

	public MyStateMachineGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyStateMachineGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
