/*
 * generated by Xtext 2.25.0
 */
package lsi.us.es.mis.xtext.ui.tests;

import com.google.inject.Injector;
import lsi.us.es.mis.xtext.statemachine.ui.internal.StatemachineActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyStateMachineUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return StatemachineActivator.getInstance().getInjector("lsi.us.es.mis.xtext.MyStateMachine");
	}

}
